{% set name = "mantis" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower}}
  version: {{ version }}

source:
  url: https://github.com/splatlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: TODO

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake>=3.9
    - zlib
    - sdsl-lite
  run:
    - zlib
    - sdsl-lite

test:
  commands:
    - mantis

about:
   home: https://github.com/splatlab/mantis
   license: BSD-3-Clause
   license_family: BSD
   license_file: LICENSE
   summary: Mantis: A Fast, Small, and Exact Large-Scale Sequence-Search Index

extra:
   identifiers:
     - doi:10.1016/j.cels.2018.05.021
