{% set name = "HowDeSBT" %}
{% set version = "1.00.00" %}
{% set sha256 = "cd9bae56e01280397fa247ffcab493b87bcfb5e06350cb83ca41d90cfc7a7355" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/medvedevgroup/HowDeSBT/archive/1.00.00.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}    
    - jellyfish 2.2.10
    - sdsl-lite
    - croaring
  host:
    - jellyfish 2.2.10
    - sdsl-lite
    - croaring
  run:
    - gcc_linux-64    # [linux]
    - clangxx_osx-64  # [osx]
    - jellyfish 2.2.10
    - sdsl-lite
    - croaring

test:
  commands:
    - howdesbt version

about:
  home: https://github.com/medvedevgroup/HowDeSBT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sequence Bloom Tree, supporting determined/how split filters
