{% set version = "3.0.4" %}

build:
  number: 0
  noarch: generic

package:
  name: mixcr
  version: {{ version }}

source:
  url: https://github.com/milaboratory/mixcr/releases/download/v{{ version }}/mixcr-{{ version }}.zip
  sha256: 6f50639190227a7cf337c567f0065ead6f5a459fa2f8084ebde937b46934f3be

about:
  home: https://github.com/milaboratory/mixcr
  license: https://github.com/milaboratory/mixcr/blob/develop/LICENSE
  summary: >
    MiXCR is a universal software for fast and accurate analysis of
    raw T- or B- cell receptor repertoire sequencing data.

requirements:
  run:
    - openjdk >=9.0.0

test:
  commands:
    - mixcr
