{% set name = "irida-uploader" %}
{% set version = "0.1" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/phac-nml/{{ name }}/archive/{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - python =3.6
    - pip
    - make
    - setuptools
    - rauth==0.7.3
    - autopep8==1.4
    - pycodestyle 
    - requests==2.21.0
    - appdirs==1.4.3
    - pytest
    - mkdocs==1.0.0
    - cerberus
    - argparse
    - selenium 

  run:
    - python =3.6
    - rauth==0.7.3
    - autopep8==1.4
    - pycodestyle 
    - requests==2.21.0
    - appdirs==1.4.3
    - pytest
    - mkdocs==1.0.0
    - cerberus
    - argparse
    - selenium 
test:
  imports:
    - irida-uploader 
  commands:
    - irida-uploader --help
    - irida-uploader --version

about:
  home: https://github.com/phac-nml/irida-uploader
  license: Apache Software License
  license_family: APACHE
  license_file: 'LICENSE'
  summary: Sequence file uploader for IRIDA
  author: Jeffrey Thiessen
  doc_url: 'https://irida-uploader.readthedocs.io/en/latest'
  dev_url: 'https://github.com/phac-nml/irida-uploader'
